services:
  arango:
    image: docker.io/arangodb
    container_name: arango
    restart: always
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: root
      ARANGO_NO_AUTH: "false"